### ISSUE TITLE
android.view.InflateException: Binary XML file line #10

### ISSUE THREAD

**Issue by prasoons** [jrejaud/ViewPagerIndicator2#4]
can you let me know what is the issue or i am doing wrong. 
I am using ViewPagerIndicator2 but while using getting error.  Added in 
`dependencies {compile 'com.github.jrejaud:ViewPagerIndicator2:0.0.1'}`
while running app, receiving below error 
`android.view.InflateException: Binary XML file line #10: Error inflating class com.viewpagerindicator.TitlePageIndicator`

Fatal Exception : Main
`FATAL EXCEPTION: main
Process: com.example.prasoon.sas10, PID: 13362
java.lang.RuntimeException: Unable to start activity ComponentInfo
{com.example.prasoon.sas10/com.example.prasoon.sas10.activity.LaunchActivity}: 
android.view.InflateException: Binary XML file line #10: Error inflating class com.viewpagerindicator.TitlePageIndicator
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2555)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2629)
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:182)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                               at android.os.Looper.loop(Looper.java:194)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5706)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1033)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class com.viewpagerindicator.TitlePageIndicator
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                               at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
 at com.example.prasoon.sas10.activity.LaunchActivity.onCreate(LaunchActivity.java:21)
                                                                               at android.app.Activity.performCreate(Activity.java:6092)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2502)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2629) 
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:182) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                               at android.os.Looper.loop(Looper.java:194) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5706) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1033) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828) 
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.viewpagerindicator.TitlePageIndicator" on path: DexPathList[[zip file "/data/app/com.example.prasoon.sas10-2/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
                                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:571)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                               at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                               at com.example.prasoon.sas10.activity.LaunchActivity.onCreate(LaunchActivity.java:21) 
                                                                               at android.app.Activity.performCreate(Activity.java:6092) 
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112) 
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2502) 
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2629) 
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:182) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                               at android.os.Looper.loop(Looper.java:194) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5706) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1033) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828) 
Suppressed: java.lang.ClassNotFoundException: com.viewpagerindicator.TitlePageIndicator
                                                                               at java.lang.Class.classForName(Native Method)
                                                                               at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                               at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                    ... 23 more
                                                                            Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
`

**Comment by jrejaud** [comment]
Did you update your XML path?
https://github.com/jrejaud/ViewPagerIndicator2#usage
